#!/usr/bin/ruby

require 'utilities'
require 'parser'
require 'scene'
require 'raytracer'
require 'camera'
require 'sampler'
require 'film'

def run_main?; __FILE__ == $0; end
# main
if run_main?
  # defaults
  ifile_name = 'input-00'
  ofile_name = 'output-00'

  # parse cl args
  i = 0
  while i < ARGV.size
    opt = ARGV[i]
    case opt
    when '-i':
      ifile_name = ARGV[i+1]
      i += 2
    when '-o':
      ofile_name = ARGV[i+1]
      i += 2
    else
      i += 1
    end
  end
  debug "input: #{ifile_name}; output: #{ofile_name}"
  
  parser = Parser.new(ifile_name)
  parser.parse()
  
  sampler = Sampler.new(parser.width, parser.height,
      parser.top_left, parser.top_right, parser.bot_left, parser.bot_right)
  camera = Camera.new(parser.camera_loc)
  raytracer = RayTracer.new(parser.shapes, parser.lights, camera)
  film = Film.new(parser.width, parser.height, ofile_name)
  scene = Scene.new(sampler, camera, raytracer, film)
  scene.render()
  
  film.output
end
