#!/usr/bin/ruby

require 'film'
require 'utilities'

def run_main?; __FILE__ == $0; end
# main
if run_main?
  # defaults
  ifile_name = 'input-00'
  ofile_name = 'output-00'

  # parse cl args
  i = 0
  while i < ARGV.size
    opt = ARGV[i]
    case opt
    when '-i':
      ifile_name = ARGV[i+1]
      i += 2
    when '-o':
      ofile_name = ARGV[i+1]
      i += 2
    else
      i += 1
    end
  end
  debug "input: #{ifile_name}; output: #{ofile_name}"
  
  
  
end
